### ISSUE TITLE
[META] 0.2.1-beta pre release checklist

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#613]
- [x] After confirming that #599 is publishing working builds, adjust so that releases are only deployed from the master branch
- [x] Draft new release node
- [x] Add detailed description / changelog to the release node
